travis:
  secure:
    BINSTAR_TOKEN: AaVXOcMlHqIu3yJxJpRfAuJfCeKRCDi2oX+zvfbkldaBzIXzjogbPEGBGZUJyiJrHzHaSvkY6N5EkguN9CcUhlC3lw4/yYpk/f0om94Ojux79dqHcn14vbBkDPMsgLC0yhqyKGjJji71H0QC8T9jDGotHC06XgKJ7t+ApcXziN+QeAaaLmdMs0HqHLppfm0SNmkLG+3y7ST39GILXoQpVYgH8YpX37yhWK3eODVXdAOT+ispnnOdbQP0Zc8A8IiJCr8rGZzys4eI8ON6sgfra42aVekZjt8wC+hdN+lJSBym+9xvct/y2mIjfMw+eBL+v2anQYfc9vEUnEwX+r1uJ4XLcm7T74ZZeQyrdD0U9zuBygHFQdlfASpIsRGyKmj5LcWvrZqiay1VNW4QOcqhqIOrmkfamDdO/sSvCg7y5wWG4lzRO8ewqF/wyyH9Shh2E1+Dq7E3DQItn4ca3Kkzbs6sUWVi6vZGeinZi++VpO00v0guGHZ97HeetZItpb6p3GRDakWkgQ/MaPE3vnEJ9njR9AA+u/iDOVIiTYhzYgFWQUtTNgdwaozIJhlbxEsZCNEmAKmpVR3ihj+N6gtFP8+qGLmSR+kS3GbyV8Nk34E9Z4XRAidr13/qC2tvQPpcj7YTNIDL7cS6xlzhBMuhx6w/U1ZGxAl1UPjaMFtvGhc=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
